apiVersion: cleanup.ibm.com/v1
kind: CleanUpOperator
metadata:
  name: cleanupoperator-localvolume
  namespace: "system"
spec:
  resourceName: "local-volume"
  namespace: "local-storage"
  version: "4.6"
